return {
  {
    key = "theme",
    type = "choice",
    label = "THEME",
    default = "clean",
    choices = {
      { "CLEAN", "clean" },
      { "RED", "red" },
      { "BLUE", "blue" },
      { "YELLOW", "yellow" },
      { "GOLD", "gold" },
      { "SILVER", "silver" },
      { "CRYSTAL", "crystal" },
      { "HIGH CONTRAST", "high_contrast" },
    },
  },
  {
    key = "dark_mode",
    type = "toggle",
    label = "DARK MODE",
    default = false,
  },
  {
    key = "ui_size",
    type = "choice",
    label = "UI SIZE",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "SMALL", "small" },
      { "MEDIUM", "medium" },
      { "LARGE", "large" },
    },
  },
  {
    key = "text_size",
    type = "choice",
    label = "TEXT SIZE",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "1X", 1 },
      { "2X", 2 },
      { "3X", 3 },
    },
  },
  {
    key = "font",
    type = "choice",
    label = "FONT",
    default = "openttd_mono",
    choices = {
      { "OPENTTD MONO", "openttd_mono" },
      { "PLAIN PIXEL", "plain_pixel" },
      { "SYSTEM", "system" },
    },
  },
  {
    key = "density",
    type = "choice",
    label = "DENSITY",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "COMFORTABLE", "comfortable" },
      { "COMPACT", "compact" },
    },
  },
  {
    key = "native_dialogue",
    type = "toggle",
    label = "NATIVE DIALOGUE",
    default = false,
  },
  {
    key = "native_menus",
    type = "toggle",
    label = "NATIVE MENUS",
    default = false,
  },
  {
    key = "native_pokemon",
    type = "toggle",
    label = "NATIVE POKEMON UI",
    default = false,
  },
  {
    key = "native_storage",
    type = "toggle",
    label = "NATIVE STORAGE",
    default = false,
  },
  {
    key = "native_services",
    type = "toggle",
    label = "NATIVE SERVICES",
    default = false,
  },
  {
    key = "native_manager",
    type = "toggle",
    label = "NATIVE MANAGER",
    default = false,
  },
}
